# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0018_hybridflow_and_clientattrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='_post_logout_redirect_uris',
            field=models.TextField(blank=True, default='', help_text='Enter each post logout URI in a new line.', verbose_name='Post logout redirect URIs'),
        ),
        migrations.AddField(
            model_name='client',
            name='frontchannel_logout_session_supported',
            field=models.BooleanField(default=False, help_text="Should this OP include the session id as parameter when calling 'frontchannel_logout_uri'?", verbose_name='Logout session required'),
        ),
        migrations.AddField(
            model_name='client',
            name='frontchannel_logout_uri',
            field=models.URLField(blank=True, help_text='URI that this OP should call when a user requests to log out', verbose_name='Front-Channel logout URI'),
        ),
    ]
