# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0019_auto_20160908_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, default=b'', upload_to=b'oidc_provider/clients', verbose_name='Logo Image'),
        ),
        migrations.AddField(
            model_name='client',
            name='terms_url',
            field=models.CharField(blank=True, default=b'', help_text='External reference to the privacy policy of the client.', max_length=255, verbose_name='Terms URL'),
        ),
        migrations.AddField(
            model_name='client',
            name='website_url',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='Website URL'),
        ),
    ]
