# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0020_auto_20160909_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='jwt_alg',
            field=models.CharField(choices=[(b'HS256', b'HS256'), (b'RS256', b'RS256')], default=b'RS256', help_text='Algorithm used to encode ID Tokens.', max_length=10, verbose_name='JWT Algorithm'),
        ),
    ]
