# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0022_auto_20170331_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='frontchannel_logout_session_supported',
            field=models.BooleanField(default=False, help_text="Should this OP include the session id as parameter when calling 'frontchannel_logout_uri'?", verbose_name='Logout session required'),
        ),
        migrations.AddField(
            model_name='client',
            name='frontchannel_logout_uri',
            field=models.URLField(blank=True, help_text='URI that this OP should call when a user requests to log out', verbose_name='Front-Channel logout URI'),
        ),
    ]
