# Generated by Django 2.0.1 on 2018-01-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from oidc_provider import settings as oidc_settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_provider', '0023_client_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=oidc_settings.get('OIDC_CLIENT_MODEL'), verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='token',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=oidc_settings.get('OIDC_CLIENT_MODEL'), verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=oidc_settings.get('OIDC_CLIENT_MODEL'), verbose_name='Client'),
        ),
    ]
