# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from oidc_provider.models import CLIENT_MODEL


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0023_client_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=CLIENT_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='token',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=CLIENT_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=CLIENT_MODEL, verbose_name='Client'),
        ),
    ]
