# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0023_auto_20180129_1518'),
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
    ]