# Generated by Django 2.2.13 on 2020-06-17 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='refresh_token_expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Refresh Token Expiration Date'),
        ),
    ]
