# Generated by Django 2.2.13 on 2020-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_token_refresh_token_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='backchannel_logout_uri',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Back-channel logout URI'),
        ),
    ]
