# Generated by Django 2.2.2 on 2019-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0028_auto_20190502_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='ae',
            field=models.SmallIntegerField(null=True, verbose_name='AE'),
        ),
        migrations.AddField(
            model_name='token',
            name='ae',
            field=models.SmallIntegerField(null=True, verbose_name='AE'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='ae',
            field=models.SmallIntegerField(null=True, verbose_name='AE'),
        ),
    ]
