# Generated by Django 4.1.4 on 2022-12-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0028_code__acr_values_token__acr_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='_acr_values',
            field=models.TextField(default=None, null=True, verbose_name='ACR'),
        ),
        migrations.AlterField(
            model_name='token',
            name='_acr_values',
            field=models.TextField(default=None, null=True, verbose_name='ACR'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='_acr_values',
            field=models.TextField(default=None, null=True, verbose_name='ACR'),
        ),
    ]
