# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-16 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_change_response_types_field_2_of_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='old_response_types',
        ),
        migrations.DeleteModel(
            name='ResponseType',
        ),
    ]
