# Generated by Django 4.1.4 on 2022-12-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_alter_code__acr_values_alter_token__acr_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='code_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code Hash'),
        ),
    ]
