# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0033_token_lookup_hash_part_3_of_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='token',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
    ]
