name: Django Tests CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["develop"]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - run: "ruff format --check --diff"
  
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - run: "ruff check --diff"

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox
      # we skip the 'ruff' env here, because we are running it in a separate 
      # parallel job already
      run: tox --skip-env ruff
